open_graph:
  enable: true
  twitter_id: skyhong2002

sidebar:
  logo:
    avatar: '[config.avatar](/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[Blog](/)'
    # wiki: '[btn.wiki](/wiki/)'
    # notes: '[Notes](/notes/)'
    more: '[more](https://skyhong2002.medium.com)'
  widgets:
    index: [welcome, recent, timeline] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, ghrepo, ghissues] # for pages using 'layout:post'
    wiki: [toc, ghrepo, ghissues, related] # for pages using 'layout:wiki'

recent:
  layout: recent
  rss: /atom.xml # pnpm i hexo-generator-feed
  limit: 5 # Count of posts

toc:
  layout: toc
  list_number: false #
  min_depth: 2
  max_depth: 5
  fallback: recent # Use a backup widget when toc does not exist.

footer:
  # social:
  #   github:
  #     icon: '<img src=“https://api.iconify.design/icon-park/github.svg”/>'
  #     url: https://github.com/skyhong2002/
  #   music:
  #     icon: '<img src=“https://api.iconify.design/ri:netease-cloud-music-line.svg”/>'
  #     url: https://stats.fm/skyhong2002/
  #   comments:
  #     icon: '<img src=“https://api.iconify.design/bx/comment-detail.svg”/>'
  #     url: https://github.com/skyhong2002/skyhon2002.github.io/issues
  #   email:
  #     icon: '<img src=“https://api.iconify.design/clarity/email-outline-badged.svg”/>'
  #     url: 'blog@skyhong.tw'
  sitemap:
    'blog': 
      - '[recent](/)'
      - '[categories](/categories/)'
      - '[tags](/tags/'
      - '[archives](/archives/)'
    'Projects': 
      - '[None](/wiki/)'
    'Social': 
      - '[friends](/friends/)'
      - '[comments](/about/#comments)'
    'More': 
      - '[GitHub](https://github.com/skyhong2002/)'
      
  content: |
    This website is built using Hexo and [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) theme.
    All the content in this blog is authorized by [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).


######## Article ########
# Articles
article:
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定横幅，是否根据 tags 作为关键词搜索横幅图片？
  auto_banner: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: 'This website is authorized by [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
  # 分享
  share: # [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5