open_graph:
  enable: true
  twitter_id: skyhong2002

sidebar:
  logo:
    title: Skychopath.
  menu:
    post: '[Blog](/)'
    # wiki: '[btn.wiki](/wiki/)'
    # notes: '[Notes](/notes/)'
    # more: '[more](/more/)'
  widgets:
    index: [welcome, about] # for home/wiki/categories/tags/archives/404 pages
    page: [] # for pages using 'layout:page'
    post: [toc] # for pages using 'layout:post'
    wiki: [] # for pages using 'layout:wiki'

recent:
  layout: recent
  rss: /atom.xml # pnpm i hexo-generator-feed
  limit: 5 # Count of posts

toc:
  layout: toc
  list_number: false #
  min_depth: 2
  max_depth: 5
  fallback: recent # Use a backup widget when toc does not exist.

footer:
  # social:
  #   github:
  #     icon: '<img src=“https://api.iconify.design/icon-park/github.svg”/>'
  #     url: https://github.com/skyhong2002/
  #   music:
  #     icon: '<img src=“https://api.iconify.design/ri:netease-cloud-music-line.svg”/>'
  #     url: https://stats.fm/skyhong2002/
  #   comments:
  #     icon: '<img src=“https://api.iconify.design/bx/comment-detail.svg”/>'
  #     url: https://github.com/skyhong2002/skyhon2002.github.io/issues
  #   email:
  #     icon: '<img src=“https://api.iconify.design/clarity/email-outline-badged.svg”/>'
  #     url: 'blog@skyhong.tw'
  sitemap:
    'blog': 
      - '[recent](/)'
      - '[categories](/categories/)'
      - '[tags](/tags/'
      - '[archives](/archives/)'
    'Projects': 
      - '[None](/wiki/)'
    'Social': 
      - '[friends](/friends/)'
      - '[comments](/about/#comments)'
    'More': 
      - '[GitHub](https://github.com/skyhong2002/)'
      
  content: |
    This website is built using Hexo and [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) theme.
    All the content in this blog is authorized by [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
